version: '3.8'
services:      
  dbct:
    container_name: dbct
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: caixatermica
        MYSQL_USER: radias
        MYSQL_PASSWORD: radias
    ports:
        - "9906:3306"
    volumes:
        - ./php/dbct:/docker-entrypoint-initdb.d

  php-apache-environment:
    container_name: php-apache
    build:
        context: ./php
        dockerfile: Dockerfile
    depends_on:
        - dbct
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: dbct
    depends_on:
        - dbct
